version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST "echo 'hi'"

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy