version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Serve docker-compose.yaml
          command: scp docker-compose.yaml $SSH_USER@$SSH_HOST:/home/ubuntu/docker-compose.yaml
      
      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST "sudo docker compose up -d"
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy