version: 2.1

orbs:
  ggshield: gitguardian/ggshield@1.1.4

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - ggshield/scan:
          name: GitGuardian Scan
          revision: $CIRCLE_SHA1
      - deploy:
          name: Deploy
          requires:
            - GitGuardian Scan

jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - checkout
      - run:
          name: Serve docker-compose.yaml
          command: scp docker-compose.yaml $SSH_USER@$SSH_HOST:/home/ubuntu/docker-compose.yaml
      
      - run:
          name: Deploy over SSH
          command: ssh $SSH_USER@$SSH_HOST "sudo docker compose up -d"
