COMPONENT_NAME = "{COMPONENT_NAME}"

ECS_CLUSTER_VPC_ID_EXPORT_NAME = "{ECS_CLUSTER_VPC_ID_EXPORT_NAME}"
ECS_CLUSTER_PRIVATE_SUBNET_ONE_EXPORT_NAME = (
    "{ECS_CLUSTER_PRIVATE_SUBNET_ONE_EXPORT_NAME}"
)
ECS_CLUSTER_PRIVATE_SUBNET_TWO_EXPORT_NAME = (
    "{ECS_CLUSTER_PRIVATE_SUBNET_TWO_EXPORT_NAME}"
)
ECS_CLUSTER_PUBLIC_SUBNET_ONE_EXPORT_NAME = (
    "{ECS_CLUSTER_PUBLIC_SUBNET_ONE_EXPORT_NAME}"
)
ECS_CLUSTER_PUBLIC_SUBNET_TWO_EXPORT_NAME = (
    "{ECS_CLUSTER_PUBLIC_SUBNET_TWO_EXPORT_NAME}"
)
ECS_CLUSTER_SECURITY_GROUP_ID_EXPORT_NAME = (
    "{ECS_CLUSTER_SECURITY_GROUP_ID_EXPORT_NAME}"
)
ECS_CLUSTER_NAME_EXPORT_NAME = "{ECS_CLUSTER_NAME_EXPORT_NAME}"

YELB_NAMESPACE_ARN_EXPORT_NAME = "{YELB_NAMESPACE_ARN_EXPORT_NAME}"
YELB_NAMESPACE_ID_EXPORT_NAME = "{YELB_NAMESPACE_ID_EXPORT_NAME}"
YELB_NAMESPACE_NAME = "{YELB_NAMESPACE_NAME}"

ECR_REPOSITORY_NAME = COMPONENT_NAME.lower()

CONTAINER_MEMORY = 2048
CONTAINER_CPU = 512
COMTAINER_PORT = {COMTAINER_PORT}
CONTAINER_ENVIRONMENT_SEARCH_DOMAIN_KEY = "SEARCH_DOMAIN"

SHOULD_ATTACH_TO_PUBLIC_ALB = {SHOULD_ATTACH_TO_PUBLIC_ALB}
ALB_PUBLIC_LISTENER_ARN_EXPORT_NAME = "{ALB_PUBLIC_LISTENER_ARN_EXPORT_NAME}"
ALB_YELP_APPLICATION_PATH = "{ALB_YELP_APPLICATION_PATH}"

HEALTH_CHECK_PATH = "{HEALTH_CHECK_PATH}"
HEALTH_CHECK_PORT = {HEALTH_CHECK_PORT}

SERVICE_NAME = COMPONENT_NAME.lower()
SERVICE_DESIRED_COUNT = {SERVICE_DESIRED_COUNT}
